# Pre-commit configuration for clever linter/test automation
repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        args: ["--fix"]
  - repo: https://github.com/pytest-dev/pytest
    rev: v8.3.1
    hooks:
      - id: pytest
        name: pytest with coverage
        entry: pytest --cov=. --cov-report=term-missing
        language: system
        pass_filenames: false
  # Custom hook for enforcing project-specific conventions (2, 3, 5, 6, 7)
  - repo: local
    hooks:
      - id: custom-lint-rules
        name: Custom Lint Rules
        entry: python scripts/custom_lint_rules.py
        language: system
        types: [python]
